# This workflow will build a Node project with Docker

name: build and push docker image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-node:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image
      with:
        image: edward8e/multi-downloader-nx
        tags: v1, latest
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}